# 개발 환경에서 base ConfigMap 위에 덮어쓸 값
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-auth-config
data:
  APP_ENV: "development"
  COGNITO_USER_POOL_ID: "ap-northeast-2_y1mKz50El"
  COGNITO_CLIENT_ID: "245uq1begv38q4ij0a743lgmhb"
